[theme]
base = "light"
primaryColor = "#a50085"
secondaryBackgroundColor = "#e0e0e2"
textColor = "#282a31"

[deprecation]
showPyplotGlobalUse = false

[server]
enableCORS = false
enableXsrfProtection = false